# Azure Key Vault Secret Provider Class
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-secrets
  namespace: nebula-system
spec:
  provider: azure
  secretObjects:
    - secretName: azure-keyvault-secret
      type: Opaque
      data:
        - objectName: db-connection-string
          key: connection-string
        - objectName: redis-connection-string
          key: redis-connection-string
  parameters:
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "CLIENT_ID"
    tenantId: "TENANT_ID"
    vaultName: "nebula-kv"
    objects: |
      array:
        - |
          objectName: db-connection-string
          objectType: secret
        - |
          objectName: redis-connection-string
          objectType: secret
